### ISSUE TITLE
Release new versions on pub

### ISSUE THREAD

**Issue by Milvintsiss** [KevMorelli/version_tracker#3]
Hello,
it would be a + if you can release the new versions of this package on pub, the last version of this package on pub was published 2 years ago!
Thanks 🙂

**Comment by KevMorelli** [comment]
Hey, sorry for the delay, the new version is published now.
I also want to thanks @Wolfteam for the changes for Flutter 3.

https://pub.dev/packages/version_tracker/changelog#220
